[project]
name = "py-judilibre"
version = "0.4.0a1"
description = "A Python client for the Judilibre API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
]

[build-system]
requires = ["uv_build >= 0.9.26, <0.10.0"]
build-backend = "uv_build"